services:
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      # for psql
      - PGDATABASE=${DB_NAME}
      - PGPASSWORD=${DB_PASSWORD}
      - PGUSER=${DB_USER}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
