ignoredBuiltDependencies:
  - unrs-resolver
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - simple-git-hooks
patchedDependencies:
  next: patches/next.patch
