allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lefthook: true
  sharp: true

minimumReleaseAge: 720

patchedDependencies:
  next: patches/next.patch

shellEmulator: true
